PROJECT = webserver
PROJECT_DESCRIPTION = New project
PROJECT_VERSION = 0.0.1

DEPS = cowboy erlsom erl_csv_generator

dep_erl_csv_generator = git https://github.com/drumanew/erl_csv_generator master

include erlang.mk
